# app.py (UPDATED)
import streamlit as st
import requests
import time

# --- Configuration ---
FASTAPI_BASE_URL = "http://localhost:8000"

st.set_page_config(layout="wide", page_title="GenAI Factory")
st.title("🤖 AI Content Generator")
st.markdown("---")

# ----------------------------------------------------------------------
# Helper Functions
# ----------------------------------------------------------------------

def generate_blog(prompt: str):
    """Calls the synchronous blog generation endpoint."""
    response = requests.post(f"{FASTAPI_BASE_URL}/generate/blog", json={"prompt": prompt})
    if response.status_code == 200:
        return response.json().get("content")
    st.error(f"Blog API Error: {response.json().get('error', 'Unknown Error')}")
    return None

def generate_image(prompt: str):
    """Calls the synchronous image generation endpoint."""
    response = requests.post(f"{FASTAPI_BASE_URL}/generate/image", json={"prompt": prompt})
    if response.status_code == 200:
        return response.json().get("image_url")
    st.error(f"Image API Error: {response.json().get('error', 'Unknown Error')}")
    return None

# The generate_video_polling function remains the same...
def generate_video_polling(prompt: str):
    """Handles the asynchronous video generation via polling."""
    
    # 1. START the Job
    start_response = requests.post(f"{FASTAPI_BASE_URL}/generate/video/start", json={"prompt": prompt})
    if start_response.status_code != 200:
        st.error(f"Failed to start video job: {start_response.json().get('error')}")
        return None

    job_id = start_response.json().get("job_id")
    st.info(f"Video job started! ID: **{job_id}**. Polling for status...")

    # 2. POLL the Status
    status = "PROCESSING"
    progress_bar = st.progress(0)
    
    MAX_POLLING_TIME = 300 
    start_time = time.time()
    
    while status == "PROCESSING" and (time.time() - start_time) < MAX_POLLING_TIME:
        time.sleep(5) # Wait 5 seconds between checks
        
        status_url = f"{FASTAPI_BASE_URL}/generate/video/status/{job_id}"
        status_response = requests.get(status_url)
        
        if status_response.status_code == 200:
            data = status_response.json()
            status = data.get("status")
            
            # Simulate progress for better user experience
            elapsed_time = time.time() - start_time
            progress_bar.progress(min(int((elapsed_time / MAX_POLLING_TIME) * 100), 99))
            
            if status == "COMPLETE":
                return data.get("video_url")
            elif status == "FAILED" or status == "ERROR":
                st.error(f"Video generation failed: {data.get('message', 'Check backend logs.')}")
                return None
        else:
            st.error(f"Error checking status: HTTP {status_response.status_code}")
            return None

    if status == "PROCESSING":
        st.warning("Video generation timed out. The job is still running on the backend.")
        
    return None

# ----------------------------------------------------------------------
# Streamlit UI Layout
# ----------------------------------------------------------------------

prompt = st.text_area("Enter your prompt for the content:", 
                      "A futuristic robot chef making a three-course meal in a neon-lit kitchen.",
                      height=100)

col1, col2, col3 = st.columns(3) # Added a column for the Image button

# --- Blog Generation Button ---
with col1:
    if st.button("Generate Blog Post (Fast)", use_container_width=True, type="primary"):
        if prompt:
            with st.spinner("Writing the blog post..."):
                blog_content = generate_blog(prompt)
            
            if blog_content:
                st.success("Blog Post Complete!")
                st.subheader("📝 Generated Blog Post")
                st.markdown(blog_content)
        else:
            st.warning("Please enter a prompt.")

# --- Image Generation Button ---
with col2:
    if st.button("Generate Image (Medium)", use_container_width=True, type="secondary"):
        if prompt:
            with st.spinner("Generating image..."):
                image_url = generate_image(prompt)
            
            if image_url:
                st.success("Image is Ready!")
                st.subheader("🖼️ Generated Image")
                st.image(image_url, caption="Generated by Imagen", use_column_width=True)
            else:
                st.error("Image generation failed.")
        else:
            st.warning("Please enter a prompt.")

# --- Video Generation Button ---
with col3:
    if st.button("Generate Video (Slow)", use_container_width=True, type="secondary"):
        if prompt:
            st.info("Video generation is slow (30s - 5m). This will continuously check the API.")
            with st.spinner("Starting video job..."):
                video_url = generate_video_polling(prompt)

            if video_url:
                st.success("Video is Ready!")
                st.subheader("🎬 Generated Video")
                st.video(video_url)
            else:
                st.error("Video generation did not complete successfully.")
        else:
            st.warning("Please enter a prompt.")